window.pokefutaData = [
    {
        "pokefuta_id":  "467",
        "name":  "イシツブテ・イワンコ・ルガルガン",
        "prefecture":  "岩手県",
        "city":  "盛岡市",
        "location":  "イシツブテ公園in盛岡",
        "address":  "岩手県盛岡市本宮字蛇屋敷地内",
        "lat":  39.694005,
        "lng":  141.128421,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/467/"
    },
    {
        "pokefuta_id":  "466",
        "name":  "アローライシツブテ・ブロロン・メルタン",
        "prefecture":  "岩手県",
        "city":  "金ケ崎町",
        "location":  "金ケ崎駅前",
        "address":  "岩手県金ケ崎町西根伊勢分25番地7",
        "lat":  39.200006,
        "lng":  141.112971,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/466/"
    },
    {
        "pokefuta_id":  "465",
        "name":  "イシツブテ・キマワリ・ヒスイガーディ",
        "prefecture":  "岩手県",
        "city":  "矢巾町",
        "location":  "ねむの木公園",
        "address":  "岩手県矢巾町駅東1丁目55",
        "lat":  39.6135292,
        "lng":  141.1498184,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/465/"
    },
    {
        "pokefuta_id":  "464",
        "name":  "イシツブテ・イワンコ・ウールー",
        "prefecture":  "岩手県",
        "city":  "雫石町",
        "location":  "道の駅 雫石あねっこ",
        "address":  "岩手県雫石町橋場坂本118-10",
        "lat":  39.706964,
        "lng":  140.874287,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/464/"
    },
    {
        "pokefuta_id":  "463",
        "name":  "イシツブテ・カジッチュ・ガブリアス",
        "prefecture":  "岩手県",
        "city":  "奥州市",
        "location":  "みずさわ観光物産センター Zプラザアテルイ",
        "address":  "岩手県奥州市水沢西町1番1号",
        "lat":  39.138288,
        "lng":  141.137353,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/463/"
    },
    {
        "pokefuta_id":  "426",
        "name":  "アローライシツブテ・マホミル・ミルタンク",
        "prefecture":  "岩手県",
        "city":  "葛巻町",
        "location":  "道の駅 くずまき高原",
        "address":  "岩手県葛巻町葛巻39-159-3",
        "lat":  39.984472,
        "lng":  141.339917,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/426/"
    },
    {
        "pokefuta_id":  "398",
        "name":  "アローライシツブテ・イシツブテ・ウソッキー",
        "prefecture":  "岩手県",
        "city":  "盛岡市",
        "location":  "道の駅 もりおか渋民 たみっと",
        "address":  "岩手県盛岡市渋民80番地42",
        "lat":  39.846667,
        "lng":  141.173111,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/398/"
    },
    {
        "pokefuta_id":  "397",
        "name":  "イシツブテ・オーガポン・カミッチュ",
        "prefecture":  "岩手県",
        "city":  "北上市",
        "location":  "展勝地公園(イシツブテ公園in北上)",
        "address":  "岩手県北上市立花13地割",
        "lat":  39.27362,
        "lng":  141.1282,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/397/"
    },
    {
        "pokefuta_id":  "323",
        "name":  "キリキザン・ゴローニャ",
        "prefecture":  "岩手県",
        "city":  "北上市",
        "location":  "北上駅前",
        "address":  "岩手県北上市川岸一丁目1(さくらPORT・スクエア)",
        "lat":  39.281115,
        "lng":  141.122747,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/323/"
    },
    {
        "pokefuta_id":  "299",
        "name":  "イシツブテ・ビーダル・プテラ",
        "prefecture":  "岩手県",
        "city":  "久慈市",
        "location":  "道の駅 いわて北三陸",
        "address":  "岩手県久慈市夏井町第7地割3-2",
        "lat":  40.225538,
        "lng":  141.781703,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/299/"
    },
    {
        "pokefuta_id":  "270",
        "name":  "イシツブテ・ヤジロン",
        "prefecture":  "岩手県",
        "city":  "一戸町",
        "location":  "いちのへ花の丘公園",
        "address":  "岩手県一戸町一戸砂森",
        "lat":  40.20885,
        "lng":  141.30468,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/270/"
    },
    {
        "pokefuta_id":  "269",
        "name":  "イシツブテ・フクスロー・ホーホー",
        "prefecture":  "岩手県",
        "city":  "九戸村",
        "location":  "道の駅 おりつめ オドデ館",
        "address":  "岩手県九戸村山屋第2地割28-1",
        "lat":  40.24854,
        "lng":  141.416759,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/269/"
    },
    {
        "pokefuta_id":  "268",
        "name":  "イシツブテ・イワンコ・ナゲツケサル",
        "prefecture":  "岩手県",
        "city":  "軽米町",
        "location":  "ミル・みるハウス敷地内",
        "address":  "岩手県軽米町晴山第22地割38",
        "lat":  40.322649,
        "lng":  141.381779,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/268/"
    },
    {
        "pokefuta_id":  "267",
        "name":  "クレセリア・ルナトーン",
        "prefecture":  "岩手県",
        "city":  "平泉町",
        "location":  "毛越寺 駐車場内",
        "address":  "岩手県平泉町平泉大沢",
        "lat":  38.986635,
        "lng":  141.108167,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/267/"
    },
    {
        "pokefuta_id":  "266",
        "name":  "イシツブテ・ミノムッチ・メブキジカ（あきのすがた）",
        "prefecture":  "岩手県",
        "city":  "西和賀町",
        "location":  "ほっとゆだ駅前",
        "address":  "岩手県西和賀町川尻40地割",
        "lat":  39.31446,
        "lng":  140.77649,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/266/"
    },
    {
        "pokefuta_id":  "265",
        "name":  "アママイコ・イシツブテ",
        "prefecture":  "岩手県",
        "city":  "紫波町",
        "location":  "オガールプラザ入口付近",
        "address":  "岩手県紫波町紫波中央駅前1丁目",
        "lat":  39.554641,
        "lng":  141.158293,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/265/"
    },
    {
        "pokefuta_id":  "264",
        "name":  "アローライシツブテ・イシツブテ・メタモン",
        "prefecture":  "岩手県",
        "city":  "岩手町",
        "location":  "道の駅 石神の丘",
        "address":  "岩手県岩手町五日市第10地割121-20",
        "lat":  39.968579,
        "lng":  141.213736,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/264/"
    },
    {
        "pokefuta_id":  "263",
        "name":  "イシツブテ・ドロバンコ・ルチャブル",
        "prefecture":  "岩手県",
        "city":  "滝沢市",
        "location":  "ビッグルーフ滝沢敷地内",
        "address":  "岩手県滝沢市下鵜飼1-15",
        "lat":  39.734,
        "lng":  141.07829,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/263/"
    },
    {
        "pokefuta_id":  "262",
        "name":  "アマルス・イシツブテ",
        "prefecture":  "岩手県",
        "city":  "八幡平市",
        "location":  "道の駅 にしね",
        "address":  "岩手県八幡平市大更第2地割154-36",
        "lat":  39.87958,
        "lng":  141.099388,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/262/"
    },
    {
        "pokefuta_id":  "261",
        "name":  "イシツブテ・ユキワラシ",
        "prefecture":  "岩手県",
        "city":  "二戸市",
        "location":  "ガダルテラス金田一入口付近",
        "address":  "岩手県二戸市金田一字湯田41",
        "lat":  40.320335,
        "lng":  141.318849,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/261/"
    },
    {
        "pokefuta_id":  "260",
        "name":  "イシツブテ・ダンゴロ・ドサイドン",
        "prefecture":  "岩手県",
        "city":  "一関市",
        "location":  "猊鼻渓 舟下り乗り場付近",
        "address":  "岩手県一関市東山町長坂字町467-1",
        "lat":  38.98958,
        "lng":  141.25527,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/260/"
    },
    {
        "pokefuta_id":  "259",
        "name":  "イシツブテ・ハスブレロ・ルンパッパ",
        "prefecture":  "岩手県",
        "city":  "遠野市",
        "location":  "蔵の道ひろば",
        "address":  "岩手県遠野市中央通り4-6",
        "lat":  39.330638,
        "lng":  141.528872,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/259/"
    },
    {
        "pokefuta_id":  "258",
        "name":  "イシツブテ・コスモッグ・レックウザ",
        "prefecture":  "岩手県",
        "city":  "花巻市",
        "location":  "花巻駅前",
        "address":  "岩手県花巻市大通り1丁目2-21",
        "lat":  39.392034,
        "lng":  141.11169,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/258/"
    },
    {
        "pokefuta_id":  "22",
        "name":  "ヨーギラス",
        "prefecture":  "岩手県",
        "city":  "住田町",
        "location":  "滝観洞観光センター",
        "address":  "岩手県住田町上有住字土倉298-81",
        "lat":  39.242903,
        "lng":  141.68432,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/22/"
    },
    {
        "pokefuta_id":  "21",
        "name":  "イワンコ",
        "prefecture":  "岩手県",
        "city":  "陸前高田市",
        "location":  "陸前高田市立図書館西側の歩道",
        "address":  "岩手県陸前高田市高田町字馬場前89-1",
        "lat":  39.01675,
        "lng":  141.628694,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/21/"
    },
    {
        "pokefuta_id":  "20",
        "name":  "サイホーン",
        "prefecture":  "岩手県",
        "city":  "大船渡市",
        "location":  "盛駅前",
        "address":  "岩手県大船渡市盛町字町13-1",
        "lat":  39.085906,
        "lng":  141.710256,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/20/"
    },
    {
        "pokefuta_id":  "19",
        "name":  "ココドラ",
        "prefecture":  "岩手県",
        "city":  "釜石市",
        "location":  "鵜住居駅前",
        "address":  "岩手県釜石市鵜住居町第16地割72-1",
        "lat":  39.326865,
        "lng":  141.887862,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/19/"
    },
    {
        "pokefuta_id":  "18",
        "name":  "ツボツボ",
        "prefecture":  "岩手県",
        "city":  "大槌町",
        "location":  "大槌駅前",
        "address":  "岩手県大槌町本町1-1",
        "lat":  39.357255,
        "lng":  141.90316,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/18/"
    },
    {
        "pokefuta_id":  "17",
        "name":  "オムナイト",
        "prefecture":  "岩手県",
        "city":  "山田町",
        "location":  "陸中山田駅前",
        "address":  "岩手県山田町川向町51-15",
        "lat":  39.464186,
        "lng":  141.951043,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/17/"
    },
    {
        "pokefuta_id":  "16",
        "name":  "イシツブテ",
        "prefecture":  "岩手県",
        "city":  "宮古市",
        "location":  "道の駅 みやこ（シートピアなあど）",
        "address":  "岩手県宮古市臨港通1-20",
        "lat":  39.639471,
        "lng":  141.969701,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/16/"
    },
    {
        "pokefuta_id":  "15",
        "name":  "ノズパス",
        "prefecture":  "岩手県",
        "city":  "田野畑村",
        "location":  "島越駅前",
        "address":  "岩手県田野畑村松前沢1-38",
        "lat":  39.916682,
        "lng":  141.938688,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/15/"
    },
    {
        "pokefuta_id":  "14",
        "name":  "チゴラス",
        "prefecture":  "岩手県",
        "city":  "岩泉町",
        "location":  "龍泉洞敷地内",
        "address":  "岩手県岩泉町岩泉字神成1-1",
        "lat":  39.86044,
        "lng":  141.796532,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/14/"
    },
    {
        "pokefuta_id":  "13",
        "name":  "タテトプス",
        "prefecture":  "岩手県",
        "city":  "普代村",
        "location":  "道の駅 青の国ふだい",
        "address":  "岩手県普代村9-5-3",
        "lat":  40.002821,
        "lng":  141.885736,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/13/"
    },
    {
        "pokefuta_id":  "12",
        "name":  "イワーク",
        "prefecture":  "岩手県",
        "city":  "野田村",
        "location":  "野田玉川駅前",
        "address":  "岩手県野田村玉川第５地割",
        "lat":  40.082726,
        "lng":  141.828678,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/12/"
    },
    {
        "pokefuta_id":  "11",
        "name":  "プテラ",
        "prefecture":  "岩手県",
        "city":  "久慈市",
        "location":  "道の駅 くじ（やませ土風館）",
        "address":  "岩手県久慈市中町2-5-6",
        "lat":  40.189742,
        "lng":  141.765832,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/11/"
    },
    {
        "pokefuta_id":  "10",
        "name":  "カブト",
        "prefecture":  "岩手県",
        "city":  "洋野町",
        "location":  "ひろの水産会館ウニーク前",
        "address":  "岩手県洋野町種市22-133-11",
        "lat":  40.406101,
        "lng":  141.719531,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/10/"
    },
    {
        "pokefuta_id":  "403",
        "name":  "ドククラゲ・ブルンゲル・プルリル・メノクラゲ",
        "prefecture":  "山形県",
        "city":  "鶴岡市",
        "location":  "鶴岡市由良コミュニティセンター",
        "address":  "山形県鶴岡市由良2-14",
        "lat":  38.721151,
        "lng":  139.684635,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/403/"
    },
    {
        "pokefuta_id":  "402",
        "name":  "アルクジラ・クマシュン・ツンベアー",
        "prefecture":  "山形県",
        "city":  "小国町",
        "location":  "道の駅 白い森おぐに",
        "address":  "山形県小国町小国小坂町616",
        "lat":  38.072713,
        "lng":  139.73128,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/402/"
    },
    {
        "pokefuta_id":  "401",
        "name":  "ガラルヒヒダルマ・テールナー・ランプラー",
        "prefecture":  "山形県",
        "city":  "大蔵村",
        "location":  "大蔵村観光協会",
        "address":  "山形県大蔵村南山451-2",
        "lat":  38.611083,
        "lng":  140.169653,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/401/"
    },
    {
        "pokefuta_id":  "400",
        "name":  "チェリム・チェリンボ",
        "prefecture":  "山形県",
        "city":  "寒河江市",
        "location":  "最上川ふるさと総合公園 虹の丘",
        "address":  "山形県寒河江市山西甲1269",
        "lat":  38.363842,
        "lng":  140.26637,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/400/"
    },
    {
        "pokefuta_id":  "399",
        "name":  "ドレディア・ポポッコ・ラフレシア",
        "prefecture":  "山形県",
        "city":  "山形市",
        "location":  "山形駅前",
        "address":  "山形県山形市双葉町1-2-38",
        "lat":  38.248477,
        "lng":  140.325854,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/399/"
    },
    {
        "pokefuta_id":  "322",
        "name":  "ハクリュー・ワシボン",
        "prefecture":  "秋田県",
        "city":  "仙北市",
        "location":  "田沢湖クニマス未来館",
        "address":  "秋田県仙北市田沢湖潟字ヨテコ沢4",
        "lat":  39.699992,
        "lng":  140.662631,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/322/"
    },
    {
        "pokefuta_id":  "321",
        "name":  "カラカラ・ガラルデスマス",
        "prefecture":  "秋田県",
        "city":  "鹿角市",
        "location":  "道の駅 かづの",
        "address":  "秋田県鹿角市花輪字新田町11-4",
        "lat":  40.181213,
        "lng":  140.785474,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/321/"
    },
    {
        "pokefuta_id":  "320",
        "name":  "オニゴーリ・グランブル・ヘルガー",
        "prefecture":  "秋田県",
        "city":  "男鹿市",
        "location":  "男鹿駅",
        "address":  "秋田県男鹿市船川港船川字新浜町1-19",
        "lat":  39.88201,
        "lng":  139.84772,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/320/"
    },
    {
        "pokefuta_id":  "319",
        "name":  "パピモッチ・ユキワラシ",
        "prefecture":  "秋田県",
        "city":  "横手市",
        "location":  "秋田ふるさと村",
        "address":  "秋田県横手市赤坂富ケ沢62-46",
        "lat":  39.293561,
        "lng":  140.545941,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/319/"
    },
    {
        "pokefuta_id":  "318",
        "name":  "イワンコ・ガーディ・バウッツェル",
        "prefecture":  "秋田県",
        "city":  "秋田市",
        "location":  "道の駅 あきた港",
        "address":  "秋田県秋田市土崎港西1丁目9-1",
        "lat":  39.752642,
        "lng":  140.061295,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/318/"
    },
    {
        "pokefuta_id":  "158",
        "name":  "ナマコブシ・バチンウニ・ユキハミ",
        "prefecture":  "青森県",
        "city":  "階上町",
        "location":  "道の駅 はしかみ",
        "address":  "青森県階上町大字道仏字耳ケ吠3-3",
        "lat":  40.458437,
        "lng":  141.608335,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/158/"
    },
    {
        "pokefuta_id":  "157",
        "name":  "イシツブテ・キャモメ",
        "prefecture":  "青森県",
        "city":  "八戸市",
        "location":  "蕪島海水浴場",
        "address":  "青森県八戸市大字鮫町鮫付近",
        "lat":  40.537937,
        "lng":  141.558034,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/157/"
    },
    {
        "pokefuta_id":  "462",
        "name":  "キテルグマ・ヌイコグマ・ヒメグマ・ラッキー",
        "prefecture":  "福島県",
        "city":  "大熊町",
        "location":  "大野駅前",
        "address":  "福島県大熊町下野上大野116-5",
        "lat":  37.4099576,
        "lng":  140.983206,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/462/"
    },
    {
        "pokefuta_id":  "461",
        "name":  "ラッキー、ゴチミル、ブリムオン",
        "prefecture":  "福島県",
        "city":  "小野町",
        "location":  "小野町ふるさと文化の館",
        "address":  "福島県小野町大字小野新町字中通2",
        "lat":  37.279216,
        "lng":  140.633912,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/461/"
    },
    {
        "pokefuta_id":  "460",
        "name":  "バオップ・ピンプク・ラッキー",
        "prefecture":  "福島県",
        "city":  "浅川町",
        "location":  "JR磐城浅川駅前",
        "address":  "福島県浅川町本町西裏（JR磐城浅川駅前広場）",
        "lat":  37.0802942,
        "lng":  140.4146001,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/460/"
    },
    {
        "pokefuta_id":  "459",
        "name":  "サメハダー・フカマル・ラッキー",
        "prefecture":  "福島県",
        "city":  "鮫川村",
        "location":  "手・まめ・館 鮫川村農産物加工・直売所",
        "address":  "福島県鮫川村大字赤阪中野字巡ヶ作116番地",
        "lat":  37.040242,
        "lng":  140.50677,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/459/"
    },
    {
        "pokefuta_id":  "458",
        "name":  "アオガラス・ヤジロン・ラッキー",
        "prefecture":  "福島県",
        "city":  "泉崎村",
        "location":  "泉崎さつき温泉 こがねの湯",
        "address":  "福島県泉崎村泉崎笹立山12-7",
        "lat":  37.157384,
        "lng":  140.314605,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/458/"
    },
    {
        "pokefuta_id":  "457",
        "name":  "ピクシー・マシェード・ラッキー",
        "prefecture":  "福島県",
        "city":  "西会津町",
        "location":  "道の駅 にしあいづ",
        "address":  "福島県西会津町野沢字下條乙1969-26",
        "lat":  37.585568,
        "lng":  139.642677,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/457/"
    },
    {
        "pokefuta_id":  "456",
        "name":  "カモネギ・チリーン・ハリマロン・ラッキー",
        "prefecture":  "福島県",
        "city":  "下郷町",
        "location":  "道の駅 しもごう",
        "address":  "福島県下郷町大字南倉沢字木賊844番地188",
        "lat":  37.203534,
        "lng":  139.916146,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/456/"
    },
    {
        "pokefuta_id":  "455",
        "name":  "イエッサン・ラッキー",
        "prefecture":  "福島県",
        "city":  "天栄村",
        "location":  "道の駅 季の里天栄",
        "address":  "福島県天栄村大字大里字天房41-2",
        "lat":  37.243406,
        "lng":  140.243722,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/455/"
    },
    {
        "pokefuta_id":  "454",
        "name":  "マフォクシー・ラッキー",
        "prefecture":  "福島県",
        "city":  "須賀川市",
        "location":  "須賀川市翠ヶ丘公園",
        "address":  "福島県須賀川市愛宕山5",
        "lat":  37.291536,
        "lng":  140.382947,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/454/"
    },
    {
        "pokefuta_id":  "376",
        "name":  "ダルマッカ・ラッキー",
        "prefecture":  "福島県",
        "city":  "白河市",
        "location":  "白河駅前",
        "address":  "福島県白河市郭内",
        "lat":  37.1296,
        "lng":  140.212974,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/376/"
    },
    {
        "pokefuta_id":  "375",
        "name":  "カプサイジ・スコヴィラン・ラッキー",
        "prefecture":  "福島県",
        "city":  "平田村",
        "location":  "ジュピアランドひらた",
        "address":  "福島県平田村大字蓬田新田字蓬田岳437",
        "lat":  37.262128,
        "lng":  140.547538,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/375/"
    },
    {
        "pokefuta_id":  "374",
        "name":  "ヤンヤンマ・ラッキー",
        "prefecture":  "福島県",
        "city":  "広野町",
        "location":  "二ツ沼総合公園",
        "address":  "福島県広野町大字下北迫字大谷地原74-1",
        "lat":  37.23297,
        "lng":  141.0018,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/374/"
    },
    {
        "pokefuta_id":  "373",
        "name":  "クルマユ・タブンネ・ピンプク・ラッキー",
        "prefecture":  "福島県",
        "city":  "国見町",
        "location":  "道の駅 国見 あつかしの郷",
        "address":  "福島県国見町大字藤田字日渡二18-1",
        "lat":  37.872639,
        "lng":  140.546861,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/373/"
    },
    {
        "pokefuta_id":  "372",
        "name":  "アブリー・ラッキー・ラルトス",
        "prefecture":  "福島県",
        "city":  "湯川村",
        "location":  "道の駅 あいづ 湯川・会津坂下",
        "address":  "福島県湯川村大字佐野目字五丁ノ目78-1",
        "lat":  37.55742,
        "lng":  139.862167,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/372/"
    },
    {
        "pokefuta_id":  "371",
        "name":  "カジリガメ・ニョロトノ・ラッキー",
        "prefecture":  "福島県",
        "city":  "棚倉町",
        "location":  "棚倉城跡",
        "address":  "福島県棚倉町大字棚倉字城跡33-7の先",
        "lat":  37.029237,
        "lng":  140.387151,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/371/"
    },
    {
        "pokefuta_id":  "370",
        "name":  "ミルタンク・メリープ・ラッキー",
        "prefecture":  "福島県",
        "city":  "鏡石町",
        "location":  "鏡石駅前",
        "address":  "福島県鏡石町中央245番地",
        "lat":  37.251117,
        "lng":  140.347153,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/370/"
    },
    {
        "pokefuta_id":  "369",
        "name":  "カイリキー・ラッキー",
        "prefecture":  "福島県",
        "city":  "会津坂下町",
        "location":  "坂下中央公園",
        "address":  "福島県会津坂下町字西南町裏甲3998番地2",
        "lat":  37.56046,
        "lng":  139.821186,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/369/"
    },
    {
        "pokefuta_id":  "287",
        "name":  "ラッキー・ロズレイド",
        "prefecture":  "福島県",
        "city":  "三春町",
        "location":  "三春きたまち蔵",
        "address":  "福島県三春町字北町10",
        "lat":  37.4433,
        "lng":  140.49124,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/287/"
    },
    {
        "pokefuta_id":  "286",
        "name":  "ハピナス・ラッキー",
        "prefecture":  "福島県",
        "city":  "古殿町",
        "location":  "道の駅 ふるどの",
        "address":  "福島県古殿町大字田口字平舘25番地",
        "lat":  37.092891,
        "lng":  140.529308,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/286/"
    },
    {
        "pokefuta_id":  "285",
        "name":  "ファイアロー・ラッキー",
        "prefecture":  "福島県",
        "city":  "矢吹町",
        "location":  "大池公園",
        "address":  "福島県矢吹町大池145",
        "lat":  37.21842,
        "lng":  140.335635,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/285/"
    },
    {
        "pokefuta_id":  "284",
        "name":  "ウパー・ラッキー",
        "prefecture":  "福島県",
        "city":  "西郷村",
        "location":  "まるごと西郷館",
        "address":  "福島県西郷村大字熊倉字折口原146",
        "lat":  37.1399,
        "lng":  140.15467,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/284/"
    },
    {
        "pokefuta_id":  "283",
        "name":  "ドレディア・ラッキー",
        "prefecture":  "福島県",
        "city":  "会津美里町",
        "location":  "伊佐須美神社",
        "address":  "福島県会津美里町字宮林甲4377番地1",
        "lat":  37.455169,
        "lng":  139.840297,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/283/"
    },
    {
        "pokefuta_id":  "282",
        "name":  "スワンナ・ハヤシガメ・ラッキー",
        "prefecture":  "福島県",
        "city":  "猪苗代町",
        "location":  "道の駅 猪苗代",
        "address":  "福島県猪苗代町大字堅田字五百苅1番地",
        "lat":  37.538088,
        "lng":  140.107569,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/282/"
    },
    {
        "pokefuta_id":  "281",
        "name":  "バニリッチ・ラッキー",
        "prefecture":  "福島県",
        "city":  "北塩原村",
        "location":  "五色沼入口観光プラザ",
        "address":  "福島県北塩原村大字桧原字剣ヶ峯1093-1055",
        "lat":  37.656148,
        "lng":  140.089446,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/281/"
    },
    {
        "pokefuta_id":  "280",
        "name":  "ゴリランダー・ラッキー",
        "prefecture":  "福島県",
        "city":  "伊達市",
        "location":  "霊山登山口",
        "address":  "福島県伊達市霊山町石田字中沢19-1",
        "lat":  37.760799,
        "lng":  140.691402,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/280/"
    },
    {
        "pokefuta_id":  "279",
        "name":  "ペロッパフ・ラッキー",
        "prefecture":  "福島県",
        "city":  "二本松市",
        "location":  "安達ヶ原ふるさと村先人館",
        "address":  "福島県二本松市安達ヶ原四丁目100番地",
        "lat":  37.593347,
        "lng":  140.464001,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/279/"
    },
    {
        "pokefuta_id":  "254",
        "name":  "フラエッテ・ラッキー",
        "prefecture":  "福島県",
        "city":  "飯舘村",
        "location":  "ふかや風の子広場前",
        "address":  "福島県飯舘村深谷字深谷前11-1",
        "lat":  37.698145,
        "lng":  140.735552,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/254/"
    },
    {
        "pokefuta_id":  "253",
        "name":  "ヒマナッツ・ラッキー",
        "prefecture":  "福島県",
        "city":  "双葉町",
        "location":  "双葉町産業交流センター",
        "address":  "福島県双葉町大字中野字高田1番地1",
        "lat":  37.45745,
        "lng":  141.02692,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/253/"
    },
    {
        "pokefuta_id":  "252",
        "name":  "クルミル・ラッキー",
        "prefecture":  "福島県",
        "city":  "昭和村",
        "location":  "道の駅 からむし織の里しょうわ ラッキー公園in昭和村",
        "address":  "福島県昭和村大字佐倉字上ノ原1番地",
        "lat":  37.325691,
        "lng":  139.630641,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/252/"
    },
    {
        "pokefuta_id":  "251",
        "name":  "ピンプク・ラッキー",
        "prefecture":  "福島県",
        "city":  "柳津町",
        "location":  "道の駅 会津柳津",
        "address":  "福島県柳津町大字柳津字下平乙161番地1",
        "lat":  37.528189,
        "lng":  139.722662,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/251/"
    },
    {
        "pokefuta_id":  "250",
        "name":  "ドッコラー・ラッキー",
        "prefecture":  "福島県",
        "city":  "南会津町",
        "location":  "南会津ふるさと物産館",
        "address":  "福島県南会津町田島字宮本東33番地1",
        "lat":  37.2057204,
        "lng":  139.7778739,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/250/"
    },
    {
        "pokefuta_id":  "249",
        "name":  "プリン・ラッキー",
        "prefecture":  "福島県",
        "city":  "郡山市",
        "location":  "開成山公園 野外音楽堂・ステージ前",
        "address":  "福島県郡山市開成1丁目5",
        "lat":  37.396784,
        "lng":  140.35612,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/249/"
    },
    {
        "pokefuta_id":  "248",
        "name":  "エルレイド・ラッキー",
        "prefecture":  "福島県",
        "city":  "会津若松市",
        "location":  "会津総合運動公園",
        "address":  "福島県会津若松市門田町大字堤沢村上164 会津総合運動公園内",
        "lat":  37.461098,
        "lng":  139.927545,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/248/"
    },
    {
        "pokefuta_id":  "247",
        "name":  "モルペコ・ラッキー",
        "prefecture":  "福島県",
        "city":  "福島市",
        "location":  "道の駅 ふくしま",
        "address":  "福島県福島市大笹生字月崎1-1",
        "lat":  37.80441,
        "lng":  140.41091,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/247/"
    },
    {
        "pokefuta_id":  "96",
        "name":  "サシカマス・ヨワシ・ラッキー",
        "prefecture":  "福島県",
        "city":  "川内村",
        "location":  "ショッピングセンター「YO-TASHI」",
        "address":  "福島県川内村大字下川内字宮ノ下25-1",
        "lat":  37.329458,
        "lng":  140.82162,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/96/"
    },
    {
        "pokefuta_id":  "95",
        "name":  "ヘラクロス・ラッキー",
        "prefecture":  "福島県",
        "city":  "田村市",
        "location":  "あぶくま洞",
        "address":  "福島県田村市滝根町菅谷字東釜山1",
        "lat":  37.344423,
        "lng":  140.674289,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/95/"
    },
    {
        "pokefuta_id":  "94",
        "name":  "カラサリス・マユルド・ラッキー",
        "prefecture":  "福島県",
        "city":  "川俣町",
        "location":  "道の駅 かわまた",
        "address":  "福島県川俣町大字鶴沢字東13-1",
        "lat":  37.667671,
        "lng":  140.57675,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/94/"
    },
    {
        "pokefuta_id":  "93",
        "name":  "キレイハナ・ラッキー",
        "prefecture":  "福島県",
        "city":  "いわき市",
        "location":  "道の駅 よつくら港",
        "address":  "福島県いわき市四倉町字5-218-1",
        "lat":  37.1073084,
        "lng":  140.9932743,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/93/"
    },
    {
        "pokefuta_id":  "92",
        "name":  "ラッキー・ラビフット",
        "prefecture":  "福島県",
        "city":  "楢葉町",
        "location":  "道の駅 ならは",
        "address":  "福島県楢葉町大字山田岡字大堤入22-1",
        "lat":  37.2501442,
        "lng":  140.9975789,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/92/"
    },
    {
        "pokefuta_id":  "91",
        "name":  "ラッキー",
        "prefecture":  "福島県",
        "city":  "浪江町",
        "location":  "道の駅 なみえ",
        "address":  "福島県浪江町大字幾世橋字知命寺60",
        "lat":  37.496395,
        "lng":  141.000919,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/91/"
    },
    {
        "pokefuta_id":  "90",
        "name":  "ギャロップ・ラッキー",
        "prefecture":  "福島県",
        "city":  "南相馬市",
        "location":  "道の駅 南相馬",
        "address":  "福島県南相馬市原町区高見町2-30-1",
        "lat":  37.63577,
        "lng":  140.983041,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/90/"
    },
    {
        "pokefuta_id":  "89",
        "name":  "ポニータ・ラッキー",
        "prefecture":  "福島県",
        "city":  "相馬市",
        "location":  "尾浜こども公園",
        "address":  "福島県相馬市尾浜字寺前111-1",
        "lat":  37.827708,
        "lng":  140.963244,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/89/"
    },
    {
        "pokefuta_id":  "88",
        "name":  "オドシシ・ラッキー",
        "prefecture":  "福島県",
        "city":  "新地町",
        "location":  "新地町文化交流センター",
        "address":  "福島県新地町駅前1丁目3番地",
        "lat":  37.878748,
        "lng":  140.925027,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/88/"
    },
    {
        "pokefuta_id":  "474",
        "name":  "ラプラス・チョンチー・ホエルコ・ウミディグダ",
        "prefecture":  "宮城県",
        "city":  "仙台市",
        "location":  "海岸公園（藤塚地区）",
        "address":  "宮城県仙台市若林区藤塚地内",
        "lat":  38.182602,
        "lng":  140.956528,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/474/"
    },
    {
        "pokefuta_id":  "447",
        "name":  "ラプラス・スワンナ・タマンタ",
        "prefecture":  "宮城県",
        "city":  "利府町",
        "location":  "加瀬沼公園",
        "address":  "宮城県宮城郡利府町加瀬新堤下",
        "lat":  38.311641,
        "lng":  140.983236,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/447/"
    },
    {
        "pokefuta_id":  "139",
        "name":  "ラプラス・ドードー・ドードリオ",
        "prefecture":  "宮城県",
        "city":  "美里町",
        "location":  "でんえん土田畑村",
        "address":  "宮城県美里町木間塚原田5",
        "lat":  38.489061,
        "lng":  141.133053,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/139/"
    },
    {
        "pokefuta_id":  "138",
        "name":  "ラプラス・バンバドロ",
        "prefecture":  "宮城県",
        "city":  "涌谷町",
        "location":  "くがね創庫",
        "address":  "宮城県涌谷町字新町裏110",
        "lat":  38.5392702,
        "lng":  141.1267433,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/138/"
    },
    {
        "pokefuta_id":  "137",
        "name":  "ラプラス・ロゼリア",
        "prefecture":  "宮城県",
        "city":  "加美町",
        "location":  "やくらい薬師の湯",
        "address":  "宮城県加美町味ヶ袋薬莱原1-76",
        "lat":  38.57215,
        "lng":  140.72859,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/137/"
    },
    {
        "pokefuta_id":  "136",
        "name":  "ラプラス・ハスブレロ",
        "prefecture":  "宮城県",
        "city":  "色麻町",
        "location":  "愛宕山公園",
        "address":  "宮城県色麻町四竃字東原1-12",
        "lat":  38.530136,
        "lng":  140.86142,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/136/"
    },
    {
        "pokefuta_id":  "135",
        "name":  "ラプラス・プルリル・ラブカス",
        "prefecture":  "宮城県",
        "city":  "大衡村",
        "location":  "万葉・おおひら館",
        "address":  "宮城県大衡村大衡字鐙沢12-2",
        "lat":  38.46943814,
        "lng":  140.8902292,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/135/"
    },
    {
        "pokefuta_id":  "134",
        "name":  "ラプラス・チュリネ",
        "prefecture":  "宮城県",
        "city":  "大郷町",
        "location":  "道の駅おおさと",
        "address":  "宮城県大郷町中村字北浦51-6",
        "lat":  38.424016,
        "lng":  140.992673,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/134/"
    },
    {
        "pokefuta_id":  "133",
        "name":  "ラプラス・タマゲタケ・ドダイトス",
        "prefecture":  "宮城県",
        "city":  "大和町",
        "location":  "大和町役場",
        "address":  "宮城県大和町吉岡まほろば一丁目1-1前",
        "lat":  38.437364,
        "lng":  140.885648,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/133/"
    },
    {
        "pokefuta_id":  "132",
        "name":  "ラプラス・ニャース・ニャスパー",
        "prefecture":  "宮城県",
        "city":  "丸森町",
        "location":  "丸森町町東公園",
        "address":  "宮城県丸森町字町東77-1",
        "lat":  37.913873,
        "lng":  140.762531,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/132/"
    },
    {
        "pokefuta_id":  "131",
        "name":  "ラプラス",
        "prefecture":  "宮城県",
        "city":  "川崎町",
        "location":  "川崎町役場",
        "address":  "宮城県川崎町前川字裏丁175-1",
        "lat":  38.177534,
        "lng":  140.643653,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/131/"
    },
    {
        "pokefuta_id":  "130",
        "name":  "ラプラス・フラベベ",
        "prefecture":  "宮城県",
        "city":  "柴田町",
        "location":  "船岡駅",
        "address":  "宮城県柴田町船岡中央1丁目1-1",
        "lat":  38.059143,
        "lng":  140.768239,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/130/"
    },
    {
        "pokefuta_id":  "129",
        "name":  "ラプラス・ベロベルト",
        "prefecture":  "宮城県",
        "city":  "村田町",
        "location":  "道の駅村田",
        "address":  "宮城県村田町大字村田字北塩内41",
        "lat":  38.119071,
        "lng":  140.717821,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/129/"
    },
    {
        "pokefuta_id":  "128",
        "name":  "ラプラス・チェリム",
        "prefecture":  "宮城県",
        "city":  "大河原町",
        "location":  "白石川公園",
        "address":  "宮城県大河原町大谷字町向116-26地先",
        "lat":  38.0485032,
        "lng":  140.738089,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/128/"
    },
    {
        "pokefuta_id":  "127",
        "name":  "ラプラス・ビーダル",
        "prefecture":  "宮城県",
        "city":  "七ヶ宿町",
        "location":  "道の駅七ヶ宿",
        "address":  "宮城県七ヶ宿町上野8-1",
        "lat":  37.982523,
        "lng":  140.46662,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/127/"
    },
    {
        "pokefuta_id":  "126",
        "name":  "ラプラス・ユキノオー",
        "prefecture":  "宮城県",
        "city":  "蔵王町",
        "location":  "蔵王町観光案内所付近",
        "address":  "宮城県蔵王町遠刈田温泉仲町34",
        "lat":  38.123663,
        "lng":  140.577192,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/126/"
    },
    {
        "pokefuta_id":  "125",
        "name":  "ラプラス・ブルー",
        "prefecture":  "宮城県",
        "city":  "富谷市",
        "location":  "とみやど",
        "address":  "宮城県富谷市富谷新町111",
        "lat":  38.398336,
        "lng":  140.8875,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/125/"
    },
    {
        "pokefuta_id":  "124",
        "name":  "ラプラス・ダグトリオ・オニスズメ",
        "prefecture":  "宮城県",
        "city":  "大崎市",
        "location":  "古川駅",
        "address":  "宮城県大崎市古川駅前大通1丁目5",
        "lat":  38.571356,
        "lng":  140.967465,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/124/"
    },
    {
        "pokefuta_id":  "123",
        "name":  "ラプラス・コアルヒー",
        "prefecture":  "宮城県",
        "city":  "栗原市",
        "location":  "道の駅路田里はなやま",
        "address":  "宮城県栗原市花山字本沢北ノ前112-1",
        "lat":  38.794479,
        "lng":  140.844403,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/123/"
    },
    {
        "pokefuta_id":  "122",
        "name":  "ラプラス・ハスボー",
        "prefecture":  "宮城県",
        "city":  "登米市",
        "location":  "平筒沼ふれあい公園",
        "address":  "宮城県登米市米山町字桜岡貝待井581-2",
        "lat":  38.616649,
        "lng":  141.235491,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/122/"
    },
    {
        "pokefuta_id":  "121",
        "name":  "ラプラス・ラティアス",
        "prefecture":  "宮城県",
        "city":  "角田市",
        "location":  "道の駅かくだ",
        "address":  "宮城県角田市枝野字北島81-1",
        "lat":  37.968694,
        "lng":  140.807077,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/121/"
    },
    {
        "pokefuta_id":  "120",
        "name":  "ラプラス・クスネ",
        "prefecture":  "宮城県",
        "city":  "白石市",
        "location":  "白石城跡",
        "address":  "宮城県白石市益岡町1-16",
        "lat":  38.002511,
        "lng":  140.61735,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/120/"
    },
    {
        "pokefuta_id":  "58",
        "name":  "ラプラス・ラッキー",
        "prefecture":  "宮城県",
        "city":  "山元町",
        "location":  "坂元駅",
        "address":  "宮城県山元町坂元字町東31-10",
        "lat":  37.923988,
        "lng":  140.900996,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/58/"
    },
    {
        "pokefuta_id":  "57",
        "name":  "ラプラス・チルット・ムックル・スバメ・マメパト",
        "prefecture":  "宮城県",
        "city":  "亘理町",
        "location":  "鳥の海公園",
        "address":  "宮城県亘理町荒浜字隈崎9-2",
        "lat":  38.04217,
        "lng":  140.915724,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/57/"
    },
    {
        "pokefuta_id":  "56",
        "name":  "ラプラス・トゲピー",
        "prefecture":  "宮城県",
        "city":  "岩沼市",
        "location":  "歩道上",
        "address":  "宮城県岩沼市中央1丁目2-13",
        "lat":  38.105296,
        "lng":  140.866325,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/56/"
    },
    {
        "pokefuta_id":  "55",
        "name":  "ラプラス",
        "prefecture":  "宮城県",
        "city":  "名取市",
        "location":  "名取市震災メモリアル公園",
        "address":  "宮城県名取市閖上五丁目",
        "lat":  38.17213,
        "lng":  140.954044,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/55/"
    },
    {
        "pokefuta_id":  "54",
        "name":  "ラプラス・ジラーチ",
        "prefecture":  "宮城県",
        "city":  "仙台市",
        "location":  "サンモール一番町",
        "address":  "宮城県仙台市青葉区一番町二丁目6-5",
        "lat":  38.258587,
        "lng":  140.872666,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/54/"
    },
    {
        "pokefuta_id":  "53",
        "name":  "ラプラス・タッツー",
        "prefecture":  "宮城県",
        "city":  "多賀城市",
        "location":  "多賀城駅前広場",
        "address":  "宮城県多賀城市中央2丁目7番地",
        "lat":  38.291943,
        "lng":  141.007158,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/53/"
    },
    {
        "pokefuta_id":  "52",
        "name":  "ラプラス・メタモン・ヒトデマン",
        "prefecture":  "宮城県",
        "city":  "七ヶ浜町",
        "location":  "七ヶ浜町観光交流センター",
        "address":  "宮城県七ヶ浜町花渕浜字館下75",
        "lat":  38.304315,
        "lng":  141.083342,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/52/"
    },
    {
        "pokefuta_id":  "51",
        "name":  "ラプラス・マイナン",
        "prefecture":  "宮城県",
        "city":  "利府町",
        "location":  "利府町役場",
        "address":  "宮城県利府町利府字新並松4",
        "lat":  38.329512,
        "lng":  140.975248,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/51/"
    },
    {
        "pokefuta_id":  "50",
        "name":  "ラプラス・プラスル",
        "prefecture":  "宮城県",
        "city":  "塩竈市",
        "location":  "本塩釜駅",
        "address":  "宮城県塩竈市海岸通200-15",
        "lat":  38.318226,
        "lng":  141.023075,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/50/"
    },
    {
        "pokefuta_id":  "49",
        "name":  "ラプラス",
        "prefecture":  "宮城県",
        "city":  "松島町",
        "location":  "松島海岸",
        "address":  "宮城県松島町松島字浪打浜地内",
        "lat":  38.368987,
        "lng":  141.061207,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/49/"
    },
    {
        "pokefuta_id":  "48",
        "name":  "ラプラス・ラティオス",
        "prefecture":  "宮城県",
        "city":  "東松島市",
        "location":  "野蒜駅",
        "address":  "宮城県東松島市野蒜ケ丘一丁目15-1",
        "lat":  38.379414,
        "lng":  141.15671,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/48/"
    },
    {
        "pokefuta_id":  "47",
        "name":  "ラプラス・ニャース・ニャビー・エネコ・ニャルマー",
        "prefecture":  "宮城県",
        "city":  "石巻市",
        "location":  "石巻市役所付近",
        "address":  "宮城県石巻市穀町14番1号",
        "lat":  38.433844,
        "lng":  141.303041,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/47/"
    },
    {
        "pokefuta_id":  "46",
        "name":  "ラプラス・キャモメ",
        "prefecture":  "宮城県",
        "city":  "女川町",
        "location":  "女川町まちなか交流館付近",
        "address":  "宮城県女川町女川浜字大原1-4",
        "lat":  38.445695,
        "lng":  141.44623,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/46/"
    },
    {
        "pokefuta_id":  "45",
        "name":  "ラプラス・オクタン",
        "prefecture":  "宮城県",
        "city":  "南三陸町",
        "location":  "南三陸ハマーレ歌津",
        "address":  "宮城県南三陸町歌津字伊里前96-1",
        "lat":  38.717061,
        "lng":  141.52115,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/45/"
    },
    {
        "pokefuta_id":  "44",
        "name":  "ラプラス・イシツブテ",
        "prefecture":  "宮城県",
        "city":  "気仙沼市",
        "location":  "気仙沼市まち・ひと・しごと交流プラザ",
        "address":  "宮城県気仙沼市南町海岸1-14",
        "lat":  38.905694,
        "lng":  141.574667,
        "officialUrl":  "https://local.pokemon.jp/manhole/desc/44/"
    }
];